CREATE DATABASE DB11;
USE DB11;

CREATE TABLE EMP
(EMP_NAME VARCHAR(20),
EMP_ID VARCHAR(12) PRIMARY KEY,
ADDRESS VARCHAR(20),
CLASS VARCHAR(20) );

DROP TABLE EMP;

DESC EMP;

INSERT INTO EMP VALUES ("ABHISHEK","ID1","MANGOL PURI","BUSINESS"),
("RIYA","ID2","RAJA PURI","ECONOMICAL"),
("SHIVANI","ID3","MADHU VIHAR","BEST CLASS"),
("SUMANT","ID4","MANGOL PURI","CHEAP CLASS"),
("KRISHNA","ID5","MANGOL PURI","CHEAP CLASS");

SELECT * FROM EMP;

CREATE TABLE ADDRESS
(ADDRESS VARCHAR(30),
AREA VARCHAR(12),
NEAR VARCHAR(20) );

DROP TABLE ADDRESS;

DESC ADDRESS;

INSERT INTO ADDRESS VALUES ("MANGOL PURI","INDRA GANDHI","GOLDY SCHOOL"),
("RAJA PURI","SIMA PUR","KIRAN SCHOOL"),
("MADHU VIHAR","BALAK NATH","SKV SCHOOL"),
("MANGOL PURI","BERI","ROLLER LOHA MANDI"),
("MANGOL PURI","BURARI","LOVELY PARK");

SELECT * FROM ADDRESS;

CREATE TABLE CHILD
(EMP_ID VARCHAR(5) PRIMARY KEY,
CHILD_NAME VARCHAR(12),
NO_OF_CHILD VARCHAR(3));

DROP TABLE CHILD;
DESC CHILD;

INSERT INTO CHILD VALUES ("ID1","KIRAN","2"),
("ID2","MANOJ","3"),
("ID3","VIKRAM","4"),
("ID4","VIKAS","2"),
("ID5","RAJPAL","5");

SELECT * FROM CHILD;

------------------------------------------------------

SELECT EMP_ID FROM emp;

SELECT EMP.EMP_ID, EMP.ADDRESS, CHILD.CHILD_NAME 
FROM EMP
INNER JOIN CHILD ON EMP.EMP_ID = CHILD.EMP_ID;